version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
    - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@host.docker.internal:5433/yugabyte
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDBzCCAe+gAwIBAgIJUO+wnnud/wJsMA0GCSqGSIb3DQEBCwUAMCExHzAdBgNV\nBAMTFmRldi1tYW16Mi1rNC5hdXRoMC5jb20wHhcNMTkwMzI0MTUzMjI0WhcNMzIx\nMTMwMTUzMjI0WjAhMR8wHQYDVQQDExZkZXYtbWFtejItazQuYXV0aDAuY29tMIIB\nIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxbym/v9KGgrMtkyF6fYsyfEL\nYhPiqaCgRoLWnqaViD8iUrcbFal71QCmSb2kmFyCFYu0rCB5843cWNQJtkcXZ4LR\n/BzFkiblUyiP1vw6wH14E9MZ2DQZUxlOjG/xo6dvWZhkYqDVSBbQya8ir0RKEJtB\negGB8qbaFRNHdBCm23oUjxzm8VKsy4NqWPK1QEwD1y4yVtoHNI8DL1PV9q64Sbor\nP5it3y3v72drzr2/gLcga/XNLCEjNfTGTNNANhjLas/OVj435pl5gqjCVdmaGUGD\njvoZvIq+YDM5a3XdYM+YB6sYhGU9W/tHVQiN43ImVyWjwSNsqaF4y0voRQlf6QID\nAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQhU/dCfQdsu2AgzOfv\nXX7cwVpz1DAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBAL4nwMvq\nnQ+V4IDTv5yMH9X70NZ8H8KaPBz1Bb+zWWMY4ApFLhWEfRmJT32HrwmegTmCngqj\nu93mNdre8rO0yVOScP7OQtOg8Jq9EVM22SCuDAooFAHeGeuNlWhjKiAABQCYgEtt\nFgA4LHbrvJk+VV4Bg2ZfFG0ghXWEUy3FuR9tkkrGtww4w7QK9hb8sCNXa0jLKJXG\nzFWdPBOo93OCbciDMw3kZiTEIWWdqt850dBt+rf2x2Z06bn2QIR24WWU/Sk+Plpg\natwe/9mC3na04qYOCZXGwoYg/H0L7lvmt3dqI0Twd+WVrZcbUh/E8VWsSLK9sf5a\nElkQDy+huOKgzb4=\n-----END CERTIFICATE-----"}'
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: xxxx
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'anonymous'
volumes:
  db_data:

